name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy_firebase:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: functions
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Create Build Info
        run: |
          date > src/resource/builddate
          echo ${{ github.ref_name }} > src/resource/version

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy_web_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: proxy_api_gui
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
    
    - name: Set Base Url
      run: echo "const baseApiUrl = $BASE_API_URL;" > lib/utils/const.dart
      env:
        BASE_API_URL: "${{ secrets.BASE_API_URL }}"

    - name: Build web
      run: flutter build web --release --base-href /$BASE_HREF/ --web-renderer html
      env:
        BASE_HREF: ${{ github.event.repository.name }}

    - name: Deploy to Github page
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-page
        FOLDER: proxy_api_gui/build/web
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MESSAGE: "🚀 deploy commit {sha} "
